Tests exception message from eval on worker context in console contains stack trace.

            function foo()
            {
                throw {a:239};
            }
            function boo()
            {
                foo();
            }
            boo();
VM:3 Uncaught Objecta: 239__proto__: Objectfoo @ VM:3boo @ VM:7(anonymous function) @ VM:9

